---
name: Syntax-Highlight-Engine-Simple-Perl
version: 0.0.1
author:
  - 'Sugama Keita <sugama@jamadam.com>'
abstract: "(EXPERIMENTAL) Perl code highlighting class"
license: perl
requires:
  Syntax::Highlight::Engine::Simple: 0
  Test::More: 0
  version: 0
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Syntax::Highlight::Engine::Simple::Perl:
    file: lib/Syntax/Highlight/Engine/Simple/Perl.pm
    version: 0.0.1
resources:
  license: http://dev.perl.org/licenses/
